name: Docker Build & Push to Docker Hub

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build-and-push:
    name: Build and Push Image on Local Infrastructure V2
    runs-on: self-hosted  # 🚀 O Runner Global da Organização vai assumir aqui!

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 🚀 SOLUÇÃO DEFINITIVA: Vincula o instalador guardado no seu host físico 
      # herdando exatamente o mesmo padrão de fallback do License Server.
      - name: Resgatar Instalador Local no Workspace
        run: |
          cp ../../3.9.0.4558336-linux-x64.zip . 2>/dev/null || \
          cp "${{ github.workspace }}/../3.9.0.4558336-linux-x64.zip" . 2>/dev/null || \
          cp /media/rodrigo/dados/docker-protheus-smartview/3.9.0.4558336-linux-x64.zip .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # 🎯 Corrigido para seguir o padrão de nomenclatura do seu ecossistema
          tags: rodrigomicrosiga/smartview-dev:3.9.0